### ISSUE TITLE
TypeError: text.charAt is not a function

### ISSUE THREAD

**Issue by andrekgb** [datalanche/json-bignum#5]
Hi and Thanks for the package. 
I'm trying to use your package to solve a problem with bigints that I receive in some json objects in a node.js restfull api.

Here is the json I send:
```
{
  "items": [
    {
      "appid": 730,
      "classid": "2222",
      "id": 99,
      "instanceid": "instanceID",
      "market_name": "Market name"
    },
    {
      "appid": 730,
      "classid": "2222",
      "id": 99,
      "instanceid": "instanceID",
      "market_name": "Market name"
    }
  ],
  "message": "Mensagem de teste",
  "user": 76561197960275584
}
```

Inside the api I use your package like this:

```
    var input = req.body;
    var input = bignumJSON.parse(input);
```

And here is the error I get.
![erro_json](https://cloud.githubusercontent.com/assets/6100485/12726229/7a8adfa4-c8e4-11e5-9d78-0f5074cec38e.png)

I have this same error in similar packages. I suspect it is my npm instalation, but i'm digging for info for hours and couldn't find anything related to it.

Thanks for any help.

**Comment by rpedela** [comment]
Is it possible to give me a small but complete example? Then I could run it myself and see if I get the same error.

**Comment by andrekgb** [comment]
Sure, here it is:

```
var bignumJSON = require('json-bignum');

var jsonObj = {
    "items": [
      {
          "appid": 730,
          "classid": "2222",
          "id": 99,
          "instanceid": "instanceID",
          "market_name": "Market name"
      },
      {
          "appid": 730,
          "classid": "2222",
          "id": 99,
          "instanceid": "instanceID",
          "market_name": "Market name"
      }
    ],
    "message": "Mensagem de teste",
    "user": 76561197960275584
};
var convertedObj = bignumJSON.parse(jsonObj);
console.log(convertedObj.user);
```

**Comment by rpedela** [comment]
I got the same error. The problem is that ```bignumJSON.parse()``` is supposed to behave identical to ```JSON.parse()``` which means it takes a string as an argument instead of an object. Here is a modified example except  ```jsonObj``` is a string and it will work correctly.

```js
var bignumJSON = require('json-bignum');

var jsonObj = '{ \
    "items": [ \
      { \
          "appid": 730, \
          "classid": "2222", \
          "id": 99, \
          "instanceid": "instanceID", \
          "market_name": "Market name" \
      }, \
      { \
          "appid": 730, \
          "classid": "2222", \
          "id": 99, \
          "instanceid": "instanceID", \
          "market_name": "Market name" \
      } \
    ], \
    "message": "Mensagem de teste", \
    "user": 76561197960275584 \
}';
var convertedObj = bignumJSON.parse(jsonObj);
console.log(convertedObj.user.toString());
```

**Comment by rpedela** [comment]
One more thing. If you want to create a JS object that uses this library, then you need to do the following:

```js
var jsonObj = {
    "items": [
      {
          "appid": 730,
          "classid": "2222",
          "id": 99,
          "instanceid": "instanceID",
          "market_name": "Market name"
      },
      {
          "appid": 730,
          "classid": "2222",
          "id": 99,
          "instanceid": "instanceID",
          "market_name": "Market name"
      }
    ],
    "message": "Mensagem de teste",
    "user": new bignumJSON.BigNumber('76561197960275584')
};
```

That will preserve any bignums otherwise JS will silently round the number.

**Comment by andrekgb** [comment]
OK. I receive an object on the api. So i will try to convert this object to string, do the parse and convert to object again.

Thanks

**Comment by Jeff406** [comment]
Hi, I'm having the same problem parsing obj using this library. The nested objects are parsed like this: 
`aProperty: [ [Object], [Object] ] }`. I need to convert this back to json but I got an error:
`undefined:1
[object Object]
 ^

SyntaxError: Unexpected token o`

**Comment by rpedela** [comment]
Can you provide a code example?

**Comment by Jeff406** [comment]
Oh, Now I know how to handle the objects with this library, thank you!

**Comment by donpdonp** [comment]
this might be considered a bug in hjson, or at least a feature waiting to happen. i was stuck with this error for some time and came across the answer just now.

```
let config = Hjson.parse(fs.readFileSync('./config.hjson'))

ERROR:
/home/donp/code/cointhink/api/node_modules/hjson/lib/hjson.js:206
      ch = text.charAt(at);
                ^

TypeError: text.charAt is not a function
```
The problem was readFileSync was returning a Buffer instead of a String. 

```
let config = Hjson.parse(fs.readFileSync('./config.hjson', 'utf8'))
// works great
```

leaving this comment here for future googlers to find as a fix since the error message is misleading.
